# ============================================================
# TAA 기금운용본부 — views.yaml (멀티 지평)
# 최종 수정: 2026-02-12 (테스트용 초기 뷰)
# ============================================================

assets: [SPY, TLT, GLD, DXY]

views:
  - id: V1
    name: "GLD 단기 조정 (금 과열 후 숨고르기)"
    P: [0, 0, 1, 0]
    Q_1m: -0.005       # -0.5% (1개월, 단기 차익실현)
    Q_3m: -0.0125      # -1.25% (3개월, speculative 레짐 오버레이 반영)
    Q_6m: 0.01         # +1.0% (6개월, 구조적 금 강세 복귀)
    conf_1m: 0.65
    conf_3m: 0.60
    conf_6m: 0.40

  - id: V2
    name: "SPY-GLD 상대뷰 (주식 금 대비 상대 강세)"
    P: [1, 0, -1, 0]
    Q_1m: 0.01          # +1% (1개월)
    Q_3m: 0.025         # +2.5% (3개월)
    Q_6m: 0.02          # +2% (6개월, 밸류에이션 부담으로 축소)
    conf_1m: 0.55
    conf_3m: 0.50
    conf_6m: 0.35

  - id: V3
    name: "TLT 소폭 상승 (금리 인하 경로 지속)"
    P: [0, 1, 0, 0]
    Q_1m: 0.003         # +0.3% (1개월, CPI 대기)
    Q_3m: 0.00875       # +0.875% (3개월)
    Q_6m: 0.02          # +2.0% (6개월, 금리 인하 누적)
    conf_1m: 0.50
    conf_3m: 0.45
    conf_6m: 0.40

  - id: V4
    name: "DXY 소폭 약세 (달러 약세 추세 지속)"
    P: [0, 0, 0, 1]
    Q_1m: -0.002        # -0.2% (1개월)
    Q_3m: -0.005        # -0.5% (3개월)
    Q_6m: -0.015        # -1.5% (6개월, 구조적 약세)
    conf_1m: 0.40
    conf_3m: 0.35
    conf_6m: 0.30

  - id: V5
    name: "SPY 상방 (경기 확장 지속)"
    P: [1, 0, 0, 0]
    Q_1m: 0.008         # +0.8% (1개월)
    Q_3m: 0.02          # +2.0% (3개월)
    Q_6m: 0.035         # +3.5% (6개월)
    conf_1m: 0.60
    conf_3m: 0.50
    conf_6m: 0.40
